import dimensions from './media-dimensions.json' with { type: 'json' };
export const personnel = [
 {image:'guard',title:'Uniformed guards',text:'A visible presence for workplaces, residences and everyday access.',service:'corporate-security',alt:'R CORPS guard in the company uniform at an entrance'},
 {image:'pso',title:'Personal security officers',text:'A personal assignment, with attention to the individual and the day ahead.',service:'personal-protection',alt:'Supplied photograph of a personal security officer beside a vehicle'},
 {image:'gunman',title:'Armed security',text:'Specialist requirements discussed against the assignment and applicable permissions.',service:'armed-security',alt:'Client-supplied photograph of an armed security team member'},
 {image:'escort',title:'Personal escorts',text:'Support around arrivals, appearances and movement between locations.',service:'escort-security',alt:'R CORPS personnel accompanying guests through an indoor arrival area'}
];
export const teamPicture=(name,alt,cls='',eager=false)=>{ const small=dimensions[name+'-640.webp'],large=dimensions[name+'-1200.webp']; return `<picture class="${cls}"><source srcset="/assets/v4/${name}-640.webp ${small.width}w${large.width>small.width?`, /assets/v4/${name}-1200.webp ${large.width}w`:``}" sizes="(max-width: 700px) 100vw, 50vw" type="image/webp"><img src="/assets/v4/${name}-1200.webp" alt="${alt}" width="${large.width}" height="${large.height}" loading="${eager?'eager':'lazy'}" ${eager?'fetchpriority="high"':''} decoding="async"></picture>`;};
export function personnelSection(arrow){return `<section class="personnel-section shell" id="personnel"><div class="personnel-heading"><div><p class="eyebrow">THE RIGHT PEOPLE FOR YOUR REQUIREMENT</p><h2>Different roles.<br><em>One considered presence.</em></h2></div><p>From everyday guarding to personal protection.<br>Start with the responsibility you need covered.</p></div><div class="personnel-grid">${personnel.map((p,i)=>`<a class="personnel-card personnel-${p.image}" href="/services/${p.service}/"><div class="personnel-photo">${teamPicture(p.image,p.alt)}<span>0${i+1}</span></div><div class="personnel-copy"><h3>${p.title} ${arrow}</h3><p>${p.text}</p></div></a>`).join('')}</div></section>`;}
export function vehicleSection(button){return `<section class="vehicle-section"><div class="shell vehicle-layout"><figure><picture><source srcset="/assets/v4/vehicle-640.webp 640w, /assets/v4/vehicle-1200.webp 1200w" sizes="(max-width:700px) 100vw, 60vw" type="image/webp"><img src="/assets/v4/vehicle-1200.webp" width="1536" height="1024" alt="Illustrative R CORPS branded escort vehicle concept with a clean roof and no emergency beacon" loading="lazy" decoding="async"></picture><figcaption>Illustrative vehicle concept · Actual vehicle and availability confirmed with your quotation.</figcaption></figure><div><p class="eyebrow light">SECURITY, THROUGH THE JOURNEY</p><h2>Your next move.<br><em>Considered.</em></h2><p>Discuss an escort vehicle for your journey, together with the personnel, timings and coordination your assignment needs.</p>${button('Discuss an escort vehicle','/get-a-quote/?service=escort-vehicle')}<a class="vehicle-details" href="/services/escort-vehicle/">Explore escort vehicle requirements ↗</a></div></div></section>`;}
