// Short, verbatim excerpts from public Google reviews, checked 28 September 2026.
// Keep the wording and attribution intact. This is a curated snapshot, not a live feed.
export const reviews = [
  { name: 'Revati Khedekar', initials: 'RK', quote: 'made all guests feel both safe & respected.', source: 'https://share.google/Xo4K6uWhXhSVLZM3h' },
  { name: 'Akash Wakle', initials: 'AW', quote: 'Excellent bouncer security service.', source: 'https://share.google/7op3tOVSHyWBNdaYW' },
  { name: 'Parth Bhalerao', initials: 'PB', quote: 'Most professional team I’ve ever worked with.', source: 'https://share.google/x3yLPQduhxyToNg1c' }
];

const escape = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
export function reviewSection(business, arrow) {
 const r=business.reviewSnapshot;
 return `<section class="review-story" id="reviews" aria-labelledby="review-heading"><div class="shell"><div class="review-heading"><div><p class="eyebrow">THEIR EXPERIENCE. THEIR WORDS.</p><h2 id="review-heading">What people say <em>about R CORPS.</em></h2></div><a class="review-google-link" href="${business.googleProfile}" target="_blank" rel="noopener noreferrer">Read all Google reviews ${arrow}</a></div>
 <div class="review-layout"><div class="review-summary"><img class="google-wordmark" src="/assets/v4/google.png" alt="Google" width="92" height="30" loading="lazy"><strong class="review-excellent">EXCELLENT</strong><div class="review-stars" role="img" aria-label="${r.rating} out of 5 stars">★★★★★</div><p><strong>${r.rating}</strong> out of 5<br> Based on <strong>${r.count} reviews</strong></p><a href="${business.googleProfile}" target="_blank" rel="noopener noreferrer">View on Google ↗</a></div>
 <div class="review-stage" role="region" aria-roledescription="carousel" aria-label="Selected Google review excerpts"><div class="review-rail" id="review-rail" tabindex="0" role="group" aria-label="Google review cards. Swipe or use arrow keys to explore.">${reviews.map((v,i)=>`<figure class="review-slide" role="group" aria-roledescription="slide" aria-label="${i+1} of ${reviews.length}: ${escape(v.name)}"><figcaption class="review-person"><img class="review-avatar" src="/assets/v4/reviewer-${['revati','akash','parth'][i]}.webp" alt="" width="42" height="42" loading="lazy"><span><strong>${escape(v.name)}</strong><small>Google review</small></span><img src="/assets/v4/google-g.png" alt="" width="22" height="22" loading="lazy"></figcaption><div class="review-stars" role="img" aria-label="5 out of 5 stars">★★★★★</div><blockquote><p>${escape(v.quote)}</p></blockquote><a class="review-read" href="${v.source}" target="_blank" rel="noopener noreferrer" aria-label="Read ${escape(v.name)}’s full review on Google">Read full review ↗</a></figure>`).join('')}</div><div class="review-controls" hidden><div class="review-dots" role="group" aria-label="Choose a review">${reviews.map((v,i)=>`<button type="button" data-review="${i}" aria-label="Show review ${i+1} by ${escape(v.name)}"><span></span></button>`).join('')}</div><span class="review-position" aria-live="polite" aria-atomic="true">01 / 03</span><div class="review-arrows"><button type="button" data-review-prev aria-label="Previous review" aria-controls="review-rail">${arrow}</button><button type="button" data-review-next aria-label="Next review" aria-controls="review-rail">${arrow}</button></div></div></div></div><p class="review-source-note">Short excerpts from original Google reviews · Rating checked <time datetime="${r.lastVerified}">${r.label}</time> · Open a review to read the full text.</p></div></section>`;
}
